{"uuid": "bce50e7e-e26a-49f7-8ef0-d4575707d319", "children": ["a3b3e246-eeb7-44eb-91d0-76e0598882ac"], "befores": [{"name": "_xunit_setup_class_fixture_TestUiCatelog", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent. Original error: xcodebuild failed with code 65. This usually indicates an issue with the local Xcode setup or WebDriverAgent project configuration or the driver-to-platform version mismatch. Consider checking the WebDriverAgent configuration guide for real iOS devices at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md.. Make sure you follow the tutorial at https://appium.github.io/appium-xcuitest-driver/latest/preparation/real-device-config/\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent. Original error: xcodebuild failed with code 65. This usually indicates an issue with the local Xcode setup or WebDriverAgent project configuration or the driver-to-platform version mismatch. Consider checking the WebDriverAgent configuration guide for real iOS devices at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md.. Make sure you follow the tutorial at https://appium.github.io/appium-xcuitest-driver/latest/preparation/real-device-config/\n    at getResponseForW3CError (/Users/pauline/.nvm/versions/node/v22.4.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)\n    at asyncHandler (/Users/pauline/.nvm/versions/node/v22.4.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at processImmediate (node:internal/timers:454:9)\n    at process.callbackTrampoline (node:internal/async_hooks:130:17)\n", "trace": "  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1125, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 880, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/python.py\", line 786, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/python.py\", line 714, in _call_with_optional_argument\n    func(arg)\n  File \"/Users/pauline/PycharmProjects/test/Ios_Test/case/test_uicatelog.py\", line 17, in setup_class\n    self.main = self.app.start().goto_main()\n  File \"/Users/pauline/PycharmProjects/test/Ios_Test/base/app.py\", line 38, in start\n    self.driver = webdriver.Remote(\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/appium/webdriver/webdriver.py\", line 229, in __init__\n    super().__init__(\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/appium/webdriver/webdriver.py\", line 320, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1720073201984, "stop": 1720073204210}], "start": 1720073201984, "stop": 1720073204306}